vim.cmd('source ~/.config/nvim/config.vim')
require('options')
require('keymaps')
require('plugins')
require('colorscheme')
require('lsp')
require('lua.config.comment')
require('lua.config.nvim-tree')
require('lua.config.lualine')
require('lua.config.telescope')
require('lua.config.nvim-cmp')
require('lua.config.autopairs')
require('lua.config.treesitter')
require('lua.config.gitsigns')
